import 'dart:math';

/// 🎯 WORD MODEL
class WordItem {
  final String word;
  final String hint;

  WordItem(this.word, this.hint);
}

/// 📂 CATEGORY MODEL
class CategoryItem {
  final String title;
  final String image;
  final List<WordItem> words;

  CategoryItem({required this.title, required this.image, required this.words});
}

/// 🎲 GAME HELPER (RANDOM LOGIC)
class GameHelper {
  static final Random _random = Random();

  /// 🎯 RANDOM CATEGORY
  static CategoryItem getRandomCategory(List<CategoryItem> categories) {
    return categories[_random.nextInt(categories.length)];
  }

  /// 🎯 RANDOM WORD FROM CATEGORY
  static WordItem getRandomWord(CategoryItem category) {
    return category.words[_random.nextInt(category.words.length)];
  }

  /// 🎯 RANDOM IMPOSTER INDEX
  static int getRandomImposter(int playerCount) {
    return _random.nextInt(playerCount);
  }

  // 🎭 multiple imposters
  static List<int> getRandomImposters(int length, int count) {
    final Set<int> result = {};

    while (result.length < count) {
      result.add(_random.nextInt(length));
    }

    return result.toList();
  }
}

// 🔥 All categories + words live here
class CategoryData {
  static List<CategoryItem> categories = [
    CategoryItem(
      title: "ANIMALS",
      image: "images/animal.png",
      words: [
        WordItem("cow", "four stomachs"),
        WordItem("buffalo", "curved horns"),
        WordItem("dog", "tail talk"),
        WordItem("cat", "silent paws"),
        WordItem("goat", "square pupils"),
        WordItem("sheep", "flock mind"),
        WordItem("horse", "hoof beats"),
        WordItem("donkey", "loud bray"),
        WordItem("camel", "fat storage"),
        WordItem("pig", "smart snout"),
        WordItem("rabbit", "rear thump"),
        WordItem("tiger", "stripe camouflage"),
        WordItem("lion", "mane crown"),
        WordItem("elephant", "trunk grip"),
        WordItem("leopard", "rosette spots"),
        WordItem("cheetah", "tear marks"),
        WordItem("wolf", "alpha rule"),
        WordItem("fox", "bushy tail"),
        WordItem("hyena", "bone crusher"),
        WordItem("bear", "hibernation mode"),
        WordItem("deer", "antler shed"),
        WordItem("zebra", "unique pattern"),
        WordItem("giraffe", "blue tongue"),
        WordItem("kangaroo", "back kick"),
        WordItem("panda", "false thumb"),
        WordItem("koala", "eucalyptus diet"),
        WordItem("monkey", "tail balance"),
        WordItem("gorilla", "chest beat"),
        WordItem("chimpanzee", "tool user"),
        WordItem("rhinoceros", "keratin horn"),
        WordItem("hippopotamus", "pink sweat"),
        WordItem("squirrel", "tail signal"),
        WordItem("rat", "maze master"),
        WordItem("mouse", "whisker sense"),
        WordItem("bat", "ultra sound"),
        WordItem("peacock", "eye feathers"),
        WordItem("crow", "face memory"),
        WordItem("sparrow", "dust bath"),
        WordItem("pigeon", "magnetic path"),
        WordItem("parrot", "curved beak"),
        WordItem("eagle", "double vision"),
        WordItem("owl", "head spin"),
        WordItem("vulture", "bald head"),
        WordItem("flamingo", "filter feed"),
        WordItem("kingfisher", "hover dive"),
        WordItem("woodpecker", "shock skull"),
        WordItem("duck", "waterproof coat"),
        WordItem("hen", "cluck code"),
        WordItem("rooster", "territory cry"),
        WordItem("swan", "pair bond"),
        WordItem("crane", "court dance"),
        WordItem("snake", "heat sense"),
        WordItem("cobra", "hood flare"),
        WordItem("python", "slow squeeze"),
        WordItem("lizard", "tail drop"),
        WordItem("gecko", "toe pads"),
        WordItem("crocodile", "death roll"),
        WordItem("alligator", "u jaw"),
        WordItem("turtle", "ocean return"),
        WordItem("tortoise", "land dome"),
        WordItem("chameleon", "eye split"),
        WordItem("frog", "skin breathe"),
        WordItem("toad", "poison glands"),
        WordItem("salamander", "limb regrow"),
        WordItem("fish", "lateral line"),
        WordItem("shark", "electro sense"),
        WordItem("whale", "long song"),
        WordItem("dolphin", "click talk"),
        WordItem("octopus", "ink escape"),
        WordItem("squid", "jet move"),
        WordItem("crab", "shell molt"),
        WordItem("lobster", "age grow"),
        WordItem("jellyfish", "no brain"),
        WordItem("seahorse", "male brood"),
        WordItem("ant", "acid bite"),
        WordItem("bee", "waggle dance"),
        WordItem("butterfly", "metamorph life"),
        WordItem("mosquito", "needle proboscis"),
        WordItem("housefly", "taste feet"),
        WordItem("cockroach", "headless run"),
        WordItem("grasshopper", "sound rub"),
        WordItem("spider", "silk spin"),
        WordItem("scorpion", "glow uv"),
      ],
    ),
    CategoryItem(
      title: "FRUITS",
      image: "images/fruit.png",
      words: [
        WordItem("apple", "Newton clue"),
        WordItem("banana", "curved peel"),
        WordItem("mango", "king fruit"),
        WordItem("orange", "segmented inside"),
        WordItem("grapes", "cluster grow"),
        WordItem("pineapple", "armored crown"),
        WordItem("papaya", "orange pulp"),
        WordItem("watermelon", "summer cube"),
        WordItem("guava", "tiny seeds"),
        WordItem("pomegranate", "jewel inside"),
        WordItem("pear", "bell shape"),
        WordItem("peach", "fuzzy skin"),
        WordItem("plum", "deep purple"),
        WordItem("cherry", "pair stem"),
        WordItem("strawberry", "surface seeds"),
        WordItem("blueberry", "color burst"),
        WordItem("raspberry", "soft clusters"),
        WordItem("blackberry", "thorn bush"),
        WordItem("cranberry", "bog fruit"),
        WordItem("mulberry", "tree drops"),
        WordItem("gooseberry", "sour spike"),
        WordItem("coconut", "liquid core"),
        WordItem("custard apple", "scaly surface"),
        WordItem("chiku", "brown sweet"),
        WordItem("jackfruit", "giant pods"),
        WordItem("lychee", "red shell"),
        WordItem("dragon fruit", "flame skin"),
        WordItem("passion fruit", "wrinkled globe"),
        WordItem("star fruit", "five points"),
        WordItem("fig", "hidden flower"),
        WordItem("dates", "desert candy"),
        WordItem("lemon", "acid burst"),
        WordItem("lime", "green acid"),
        WordItem("sweet lime", "mild citrus"),
        WordItem("grapefruit", "bitter citrus"),
        WordItem("tangerine", "loose peel"),
        WordItem("mandarin", "easy peel"),
        WordItem("kiwi", "hairy skin"),
        WordItem("avocado", "fat fruit"),
        WordItem("apricot", "soft orange"),
        WordItem("nectarine", "smooth peach"),
        WordItem("persimmon", "orange glow"),
        WordItem("plumcot", "hybrid mix"),
        WordItem("muskmelon", "fragrant sphere"),
        WordItem("cantaloupe", "netted skin"),
        WordItem("honeydew melon", "pale sweetness"),
        WordItem("jamun", "purple stain"),
        WordItem("ber", "mini apple"),
        WordItem("wood apple", "hard shell"),
        WordItem("bael", "sacred pulp"),
        WordItem("tamarind", "sticky pod"),
        WordItem("karonda", "thorn berry"),
        WordItem("kokum", "deep red extract"),
      ],
    ),
    CategoryItem(
      title: "FOOD",
      image: "images/Food.png",
      words: [
        WordItem("roti", "tawa cooked"),
        WordItem("rice", "grain staple"),
        WordItem("dal", "lentil base"),
        WordItem("paneer", "milk solid"),
        WordItem("butter chicken", "creamy spice"),
        WordItem("biryani", "layered feast"),
        WordItem("pulao", "one-pot rice"),
        WordItem("samosa", "triangular crunch"),
        WordItem("kachori", "stuffed shell"),
        WordItem("pakora", "deep fried batter"),
        WordItem("chole bhature", "chickpea combo"),
        WordItem("rajma", "red bean curry"),
        WordItem("dosa", "thin crisp wrap"),
        WordItem("idli", "steamed soft cake"),
        WordItem("vada", "fried round batter"),
        WordItem("upma", "semolina stir"),
        WordItem("poha", "flattened grain"),
        WordItem("paratha", "stuffed flatbread"),
        WordItem("aloo paratha", "potato filled"),
        WordItem("pav bhaji", "spiced mash"),
        WordItem("misal pav", "sprouted curry"),

        WordItem("pizza", "cheese circle"),
        WordItem("burger", "stacked bun"),
        WordItem("sandwich", "bread layers"),
        WordItem("fries", "potato sticks"),
        WordItem("noodles", "wheat strands"),
        WordItem("pasta", "Italian dough"),
        WordItem("momos", "steamed pockets"),
        WordItem("spring roll", "crispy wrap"),
        WordItem("hot dog", "sausage bun"),
        WordItem("taco", "folded shell"),
        WordItem("wrap", "rolled filling"),

        WordItem("cake", "layered sponge"),
        WordItem("pastry", "flaky crust"),
        WordItem("brownie", "dense chocolate"),
        WordItem("chocolate", "cocoa bar"),
        WordItem("ice cream", "frozen cream"),
        WordItem("donut", "ring sweet"),

        WordItem("gulab jamun", "sugar dunk"),
        WordItem("rasgulla", "spongy syrup"),
        WordItem("jalebi", "spiral fry"),
        WordItem("laddu", "round sweet"),
        WordItem("barfi", "milk fudge"),
        WordItem("kheer", "rice dessert"),
        WordItem("halwa", "slow stir"),

        WordItem("soup", "liquid comfort"),
        WordItem("salad", "raw mix"),
        WordItem("curry", "spiced gravy"),
        WordItem("stew", "slow simmer"),

        WordItem("sushi", "vinegared roll"),
        WordItem("ramen", "broth noodles"),
        WordItem("dumplings", "filled folds"),

        WordItem("bread", "baked loaf"),
        WordItem("toast", "crisp bread"),
        WordItem("omelette", "beaten fold"),
        WordItem("pancake", "pan flip"),
        WordItem("waffle", "grid cake"),
        WordItem("cornflakes", "breakfast crunch"),
      ],
    ),
    CategoryItem(
      title: "OBJECTS",
      image: "images/objects.png",
      words: [
        WordItem("chair", "sit support"),
        WordItem("table", "flat support"),
        WordItem("bed", "sleep zone"),
        WordItem("sofa", "soft seating"),
        WordItem("door", "entry barrier"),
        WordItem("window", "light frame"),
        WordItem("mirror", "reflection view"),
        WordItem("clock", "time keeper"),
        WordItem("fan", "air spinner"),
        WordItem("light", "brightness source"),
        WordItem("bulb", "glow capsule"),
        WordItem("switch", "power toggle"),
        WordItem("curtain", "window cover"),
        WordItem("carpet", "floor softener"),
        WordItem("pillow", "head rest"),
        WordItem("blanket", "warm cover"),

        WordItem("phone", "pocket caller"),
        WordItem("laptop", "portable work"),
        WordItem("computer", "digital brain"),
        WordItem("keyboard", "typing grid"),
        WordItem("mouse", "cursor tool"),
        WordItem("charger", "energy refill"),
        WordItem("headphones", "private sound"),
        WordItem("speaker", "sound booster"),
        WordItem("remote", "wireless control"),
        WordItem("camera", "moment capture"),
        WordItem("television", "screen box"),
        WordItem("tablet", "touch slate"),

        WordItem("pen", "ink writer"),
        WordItem("pencil", "erasable writer"),
        WordItem("eraser", "mistake remover"),
        WordItem("sharpener", "point maker"),
        WordItem("notebook", "page stack"),
        WordItem("book", "knowledge block"),
        WordItem("marker", "bold ink"),
        WordItem("highlighter", "attention ink"),
        WordItem("ruler", "measure guide"),
        WordItem("scissors", "cut tool"),
        WordItem("glue", "stick liquid"),
        WordItem("stapler", "paper binder"),

        WordItem("plate", "food base"),
        WordItem("bowl", "deep holder"),
        WordItem("spoon", "scoop tool"),
        WordItem("fork", "prong tool"),
        WordItem("knife", "slice edge"),
        WordItem("glass", "drink holder"),
        WordItem("cup", "small mug"),
        WordItem("mug", "hot drink holder"),
        WordItem("bottle", "liquid container"),

        WordItem("pan", "flat cooker"),
        WordItem("cooker", "pressure pot"),
        WordItem("stove", "heat source"),
        WordItem("fridge", "cold box"),
        WordItem("microwave", "quick heater"),

        WordItem("toothbrush", "oral cleaner"),
        WordItem("toothpaste", "cleaning paste"),
        WordItem("soap", "foam cleaner"),
        WordItem("shampoo", "hair wash"),
        WordItem("towel", "dry cloth"),
        WordItem("comb", "hair arranger"),
        WordItem("razor", "shave blade"),

        WordItem("bucket", "water carrier"),
        WordItem("bag", "carry pouch"),
        WordItem("wallet", "money holder"),
        WordItem("key", "unlock tool"),
        WordItem("lock", "security block"),

        WordItem("umbrella", "rain shield"),
        WordItem("torch", "hand light"),
        WordItem("candle", "wax flame"),
        WordItem("matchbox", "fire starter"),
        WordItem("rope", "tie strand"),
        WordItem("box", "storage cube"),
        WordItem("hanger", "clothes holder"),
        WordItem("dustbin", "waste bin"),

        WordItem("tripod", "stable stand"),
        WordItem("magnet", "metal attractor"),
        WordItem("compass", "direction finder"),
        WordItem("thermometer", "heat reader"),
        WordItem("binoculars", "far viewer"),
        WordItem("calculator", "number solver"),
        WordItem("stopwatch", "time tracker"),
        WordItem("whistle", "sound signal"),
        WordItem("helmet", "head shield"),
        WordItem("trophy", "win symbol"),
      ],
    ),
    CategoryItem(
      title: "CELEBRITIES",
      image: "images/celebrities.png",
      words: [
        WordItem("shah rukh khan", "romance king"),
        WordItem("salman khan", "bhai image"),
        WordItem("deepika padukone", "padmavat lead"),
        WordItem("akshay kumar", "action machine"),
        WordItem("virat kohli", "aggressive chase"),
        WordItem("rohit sharma", "double century man"),

        WordItem("lionel messi", "left foot magic"),
        WordItem("cristiano ronaldo", "hard work icon"),
        WordItem("lebron james", "king of court"),
        WordItem("serena williams", "power tennis queen"),
        WordItem("roger federer", "elegant strokes"),
        WordItem("rafael nadal", "clay dominance"),

        WordItem("taylor swift", "eras storyteller"),
        WordItem("beyonce", "stage energy"),
        WordItem("rihanna", "fenty empire"),

        WordItem("brad pitt", "classic hollywood face"),
        WordItem("angelina jolie", "tomb raider fame"),
        WordItem("will smith", "fresh prince"),
        WordItem("zendaya", "young style icon"),

        WordItem("robert downey jr", "iron suit genius"),
        WordItem("gal gadot", "wonder warrior"),
        WordItem("dwayne johnson", "rock persona"),
        WordItem("scarlett johansson", "black widow"),
        WordItem("chris evans", "shield carrier"),
        WordItem("emma watson", "magic school fame"),

        WordItem("leonardo dicaprio", "oscars chase"),
        WordItem("margot robbie", "barbie star"),
        WordItem("tom hanks", "forrest voice"),
        WordItem("jennifer lawrence", "hunger games lead"),
        WordItem("chris hemsworth", "hammer wielder"),

        WordItem("amitabh bachchan", "shahenshah voice"),
        WordItem("aamir khan", "perfectionist cinema"),
        WordItem("ranbir kapoor", "romantic rebel"),
        WordItem("ranveer singh", "energy explosion"),
        WordItem("hrithik roshan", "dance perfection"),
        WordItem("ajay devgn", "intense silence"),

        WordItem("kartik aaryan", "monologue fame"),
        WordItem("varun dhawan", "mass entertainer"),
        WordItem("sidharth malhotra", "student debut"),
        WordItem("vicky kaushal", "uri soldier"),
        WordItem("prabhas", "baahubali hero"),
        WordItem("allu arjun", "stylish star"),

        WordItem("ram charan", "rrr flame"),
        WordItem("mahesh babu", "tollywood prince"),

        WordItem("katrina kaif", "dance precision"),
        WordItem("alia bhatt", "young powerhouse"),
        WordItem("kareena kapoor", "poise queen"),
        WordItem("shraddha kapoor", "aashiqui voice"),
        WordItem("kriti sanon", "model to cinema"),
        WordItem("kiara advani", "kabir singh fame"),

        WordItem("taapsee pannu", "bold roles"),
        WordItem("anushka sharma", "production venture"),
        WordItem("rashmika mandanna", "national crush"),
        WordItem("samantha ruth prabhu", "strong roles"),
        WordItem("kajal aggarwal", "telugu star"),
        WordItem("tamannaah bhatia", "milky beauty"),

        WordItem("ms dhoni", "finisher calm"),
        WordItem("sachin tendulkar", "god of cricket"),
        WordItem("hardik pandya", "flamboyant allrounder"),
        WordItem("kl rahul", "stylish opener"),
        WordItem("jasprit bumrah", "sling action"),
        WordItem("ravindra jadeja", "sir jadeja"),
        WordItem("rishabh pant", "aggressive keeper"),
        WordItem("shubman gill", "next gen elegance"),

        WordItem("arijit singh", "melancholy voice"),
        WordItem("neha kakkar", "party vocals"),
        WordItem("atif aslam", "soulful intensity"),
        WordItem("armaan malik", "smooth playback"),
        WordItem("badshah", "rap beats"),
        WordItem("honey singh", "party rap era"),
        WordItem("shreya ghoshal", "melody queen"),
        WordItem("sonu nigam", "classic playback"),
      ],
    ),
    CategoryItem(
      title: "ANIME",
      image: "images/anime.png",
      words: [
        WordItem("yuji itadori", "curse vessel"),
        WordItem("megumi fushiguro", "shadow summons"),
        WordItem("nobara kugisaki", "hammer nails"),
        WordItem("satoru gojo", "limitless eyes"),
        WordItem("ryomen sukuna", "king of curses"),
        WordItem("maki zenin", "curse-free strength"),
        WordItem("toge inumaki", "cursed speech"),
        WordItem("panda", "experiment curse"),
        WordItem("yuta okkotsu", "special grade bond"),
        WordItem("rika orimoto", "love curse"),
        WordItem("kento nanami", "overtime sorcerer"),
        WordItem("mei mei", "money driven bird"),
        WordItem("ui ui", "sister protector"),
        WordItem("masamichi yaga", "puppet creator"),
        WordItem("shoko ieiri", "reverse healer"),
        WordItem("mai zenin", "bullet twin"),
        WordItem("naobito zenin", "frame speed"),
        WordItem("naoya zenin", "arrogant heir"),
        WordItem("mahito", "soul toucher"),
        WordItem("jogo", "volcano head"),
        WordItem("hanami", "forest curse"),
        WordItem("dagan", "beach curse"),
        WordItem("kenjaku", "body hopper"),
        WordItem("choso", "blood manipulation"),
        WordItem("eso", "poison sibling"),
        WordItem("kechizu", "decay sibling"),
        WordItem("toji fushiguro", "heavenly restriction"),
        WordItem("kasumi miwa", "simple sword"),
        WordItem("kokichi muta", "mech puppet"),
        WordItem("noritoshi kamo", "blood clan"),
        WordItem("takuma ino", "horn mask"),
        WordItem("atsuya kusakabe", "basic swordsman"),
        WordItem("hiromi higuruma", "court curse"),
        WordItem("kinji hakari", "slot gambler"),
        WordItem("kirara hoshi", "star love mark"),
        WordItem("remi", "pinned ally"),
        WordItem("hajime kashimo", "lightning user"),
        WordItem("angel", "fallen technique"),
        WordItem("yuki tsukumo", "anti gravity"),
        WordItem("uta hime", "sound barrier"),
        WordItem("akari nitta", "assistant aid"),
        WordItem("takako uro", "sky control"),

        WordItem("naruto", "nine tails"),
        WordItem("sasuke", "revenge path"),
        WordItem("sakura", "healing punch"),
        WordItem("kakashi", "copy ninja"),
        WordItem("itachi", "genjutsu eyes"),
        WordItem("madara", "war legend"),

        WordItem("goku", "saiyan growth"),
        WordItem("vegeta", "pride warrior"),
        WordItem("gohan", "hidden rage"),
        WordItem("piccolo", "namek fusion"),
        WordItem("frieza", "galaxy tyrant"),
        WordItem("cell", "perfect bio"),
        WordItem("broly", "limit breaker"),
        WordItem("trunks", "time traveler"),
        WordItem("krillin", "human fighter"),
        WordItem("bulma", "tech genius"),

        WordItem("luffy", "rubber pirate"),
        WordItem("zoro", "three sword"),
        WordItem("nami", "weather thief"),
        WordItem("sanji", "kicking cook"),
        WordItem("usopp", "long nose shooter"),
        WordItem("chopper", "reindeer doctor"),
        WordItem("robin", "history hands"),
        WordItem("franky", "cyborg shipwright"),
        WordItem("brook", "soul musician"),
        WordItem("jinbe", "fishman helmsman"),
        WordItem("kaido", "dragon beast"),
        WordItem("big mom", "soul empire"),
        WordItem("shanks", "red hair aura"),
        WordItem("ace", "fire fist"),

        WordItem("tanjiro", "water breath"),
        WordItem("nezuko", "demon sibling"),
        WordItem("zenitsu", "sleep lightning"),
        WordItem("inosuke", "boar head"),
        WordItem("rengoku", "flame pillar"),

        WordItem("loid forger", "master of disguises"),
        WordItem("yor forger", "assassin elegance"),
        WordItem("anya forger", "mind reading child"),
        WordItem("bond forger", "future sight dog"),

        WordItem("fiona frost", "ice expression spy"),
        WordItem("henry henderson", "elegance teacher"),
        WordItem("becky blackbell", "rich school friend"),
        WordItem("damian desmond", "elite heir rival"),
        WordItem("yuri briar", "secret police brother"),
        WordItem("sylvia sherwood", "handler eye patch"),
        WordItem("donovan desmond", "silent political figure"),
        WordItem("melinda desmond", "hidden calm mother"),

        WordItem("nightfall", "cold rival agent"),
        WordItem("fiona", "one sided affection spy"),

        WordItem("martha marriott", "royal etiquette aide"),
        WordItem("bill watkins", "child boxing prodigy"),
        WordItem("emile elman", "follower twin"),
        WordItem("emmanuel sturgeon", "follower twin"),

        WordItem("eren yeager", "freedom obsession"),
        WordItem("mikasa ackerman", "scarf protector"),
        WordItem("armin arlert", "strategy mind"),
        WordItem("levi ackerman", "clean freak soldier"),
        WordItem("erwin smith", "sacrifice commander"),
        WordItem("reiner braun", "double identity"),
        WordItem("annie leonhart", "crystal sleeper"),
        WordItem("zeke yeager", "beast lineage"),
        WordItem("historia reiss", "hidden queen"),
        WordItem("connie springer", "village survivor"),
        WordItem("sasha blous", "food obsession scout"),
        WordItem("falco grice", "wing candidate"),
        WordItem("gabi braun", "shooter rage kid"),
        WordItem("pieck finger", "cart titan brain"),

        WordItem("light yagami", "death notebook"),
        WordItem("l lawliet", "logic crouch"),
        WordItem("ryuk", "apple shinigami"),
        WordItem("misa amane", "idol obsession"),
        WordItem("near", "toy strategist"),
        WordItem("mello", "chocolate rival"),

        WordItem("edward elric", "alchemy arm"),
        WordItem("alphonse elric", "armor soul"),
        WordItem("roy mustang", "snap flame"),
        WordItem("winry rockbell", "mechanic healer"),
        WordItem("scar", "alchemy mark"),

        WordItem("gon freecss", "nen instinct"),
        WordItem("killua zoldyck", "assassin kid"),
        WordItem("kurapika", "scarlet rage"),
        WordItem("hisoka", "card clown"),
        WordItem("chrollo lucilfer", "stolen abilities"),

        WordItem("midoriya izuku", "one for all heir"),
        WordItem("bakugo katsuki", "explosion temper"),
        WordItem("todoroki shoto", "fire ice split"),
        WordItem("all might", "symbol of peace"),
        WordItem("uraraka ochaco", "gravity touch"),
        WordItem("tenya iida", "engine legs"),
        WordItem("shigaraki tomura", "decay touch"),
        WordItem("dabi", "blue flame scars"),

        WordItem("natsu dragneel", "fire dragon slayer"),
        WordItem("lucy heartfilia", "celestial keys"),
        WordItem("erza scarlet", "armor switcher"),
        WordItem("gray fullbuster", "ice maker"),

        WordItem("rimuru tempest", "slime evolution"),
        WordItem("benimaru", "flame general"),
        WordItem("shion", "chaos secretary"),
        WordItem("shuna", "princess healer"),
        WordItem("diablo", "devoted demon"),
        WordItem("milim nava", "chaos dragon child"),
        WordItem("veldora tempest", "storm sealed dragon"),

        WordItem("naruto uzumaki", "shadow clone leader"),
        WordItem("hinata hyuga", "byakugan gaze"),
        WordItem("gaara", "sand jinchuriki"),
        WordItem("orochimaru", "snake experimenter"),
        WordItem("jiraiya", "toad sage"),
        WordItem("tsunade", "medical strength"),

        WordItem("meliodas", "demon captain"),
        WordItem("elizabeth liones", "curse cycle"),
        WordItem("ban", "immortal thief"),
        WordItem("merlin", "infinity mage"),
        WordItem("escanoor", "sun pride"),

        WordItem("saitama", "one punch end"),
        WordItem("genos", "cyborg disciple"),
        WordItem("garou", "hero hunter"),
        WordItem("blast", "unknown hero"),

        WordItem("shinra kusakabe", "devil flame runner"),
        WordItem("arthur boyle", "king delusion knight"),
        WordItem("benimaru shinmon", "flame pillar soldier"),

        WordItem("asuna", "sword healer"),
        WordItem("kirito", "dual blade solo"),

        WordItem("kirishima eijiro", "hardening hero"),
        WordItem("mina ashido", "acid dancer"),

        WordItem("ichigo kurosaki", "soul reaper hybrid"),
        WordItem("rukia kuchiki", "ice spirit cutter"),
        WordItem("byakuya kuchiki", "noble petals"),
        WordItem("renji abarai", "snake blade"),
        WordItem("kenpachi zaraki", "battle hunger"),
        WordItem("toushiro hitsugaya", "ice captain"),
        WordItem("aizen sosuke", "illusion master"),
        WordItem("yhwach", "future absorber"),
        WordItem("urahara kisuke", "hat scientist"),
        WordItem("yoruichi shihouin", "flash step cat"),

        WordItem("asta", "anti magic boy"),
        WordItem("yuno", "wind rival"),
        WordItem("noelle silva", "royal water mage"),
        WordItem("yami sukehiro", "dark captain"),
        WordItem("nacht", "devil shadow user"),
        WordItem("mereoleona", "lion fire fury"),
        WordItem("licht", "elf leader"),
        WordItem("zagred", "word devil"),
        WordItem("vanessa", "thread fate"),
        WordItem("gauche adlai", "mirror obsession"),
      ],
    ),

    CategoryItem(
      title: "COUNTRIES",
      image: "images/countries.png",
      words: [
        WordItem("afghanistan", "landlocked mountains"),
        WordItem("albania", "double eagle flag"),
        WordItem("algeria", "largest africa land"),
        WordItem("andorra", "pyrenean microstate"),
        WordItem("angola", "oil rich coast"),
        WordItem("antigua and barbuda", "dual island nation"),
        WordItem("argentina", "southern football giant"),
        WordItem("armenia", "ancient christian land"),
        WordItem("australia", "island continent"),
        WordItem("austria", "alpine music land"),
        WordItem("azerbaijan", "fire land name"),

        WordItem("bahamas", "turquoise island chain"),
        WordItem("bahrain", "island kingdom oil"),
        WordItem("bangladesh", "river delta nation"),
        WordItem("barbados", "caribbean coral island"),
        WordItem("belarus", "eastern forest plains"),
        WordItem("belgium", "chocolate waffle land"),
        WordItem("belize", "central america coast"),
        WordItem("benin", "voodoo heritage coast"),
        WordItem("bhutan", "gross happiness kingdom"),
        WordItem("bolivia", "salt flats highland"),

        WordItem("bosnia and herzegovina", "balkan mixed history"),
        WordItem("botswana", "diamond desert land"),
        WordItem("brazil", "rainforest football nation"),
        WordItem("brunei", "tiny rich sultanate"),
        WordItem("bulgaria", "balkan rose valley"),

        WordItem("burkina faso", "west africa inland"),
        WordItem("burundi", "great lakes hills"),

        WordItem("cabo verde", "atlantic island cluster"),
        WordItem("cambodia", "ancient temple empire"),
        WordItem("cameroon", "miniature africa shape"),
        WordItem("canada", "maple snow giant"),
        WordItem("central african republic", "heart of continent"),
        WordItem("chad", "desert lake nation"),
        WordItem("chile", "long narrow coast"),
        WordItem("china", "great wall origin"),
        WordItem("colombia", "coffee mountain land"),

        WordItem("comoros", "perfume islands"),
        WordItem("congo", "rainforest basin"),
        WordItem("democratic republic of the congo", "huge central jungle"),
        WordItem("costa rica", "eco paradise land"),
        WordItem("croatia", "adriatic coastline"),
        WordItem("cuba", "caribbean revolution island"),

        WordItem("cyprus", "mediterranean split island"),
        WordItem("czech republic", "prague heartland"),
        WordItem("denmark", "flat bicycle nation"),
        WordItem("djibouti", "horn of africa port"),

        WordItem("dominica", "nature island volcano"),
        WordItem("dominican republic", "shared island east"),

        WordItem("ecuador", "equator sits here"),
        WordItem("egypt", "pyramids nile land"),
        WordItem("el salvador", "smallest central america"),
        WordItem("equatorial guinea", "oil tiny mainland"),
        WordItem("eritrea", "red sea coast"),
        WordItem("estonia", "digital baltic state"),
        WordItem("eswatini", "mountain monarchy"),
        WordItem("ethiopia", "ancient highland origin"),

        WordItem("fiji", "pacific island paradise"),
        WordItem("finland", "thousand lakes cold"),
        WordItem("france", "eiffel fashion nation"),

        WordItem("gabon", "equatorial rainforest oil"),
        WordItem("gambia", "river strip country"),
        WordItem("georgia", "caucasus crossroads"),
        WordItem("germany", "engineering powerhouse"),
        WordItem("ghana", "gold coast africa"),
        WordItem("greece", "ancient olympics origin"),
        WordItem("grenada", "spice island nation"),
        WordItem("guatemala", "maya volcano land"),
        WordItem("guinea", "bauxite rich coast"),

        WordItem("guinea-bissau", "small west africa coast"),
        WordItem("guyana", "forest english speaking"),
        WordItem("haiti", "revolution shared island"),
        WordItem("honduras", "central america jungle"),
        WordItem("hungary", "danube basin nation"),

        WordItem("iceland", "fire ice land"),
        WordItem("india", "diverse subcontinent"),
        WordItem("indonesia", "volcanic island chain"),
        WordItem("iran", "ancient persia land"),
        WordItem("iraq", "mesopotamia cradle"),
        WordItem("ireland", "emerald island"),
        WordItem("israel", "holy land region"),
        WordItem("italy", "boot shaped peninsula"),

        WordItem("jamaica", "reggae island"),
        WordItem("japan", "rising sun islands"),
        WordItem("jordan", "petra desert land"),

        WordItem("kazakhstan", "largest landlocked asia"),
        WordItem("kenya", "savannah safari land"),
        WordItem("kiribati", "scattered pacific atolls"),
        WordItem("kuwait", "oil gulf state"),
        WordItem("kyrgyzstan", "mountain nomad land"),

        WordItem("laos", "landlocked buddhist nation"),
        WordItem("latvia", "baltic forest coast"),
        WordItem("lebanon", "cedar mountain land"),
        WordItem("lesotho", "mountain kingdom"),
        WordItem("liberia", "africa flag roots"),
        WordItem("libya", "sahara coastal desert"),

        WordItem("liechtenstein", "tiny alpine principality"),
        WordItem("lithuania", "amber baltic shore"),
        WordItem("luxembourg", "rich microstate"),

        WordItem("madagascar", "island of lemurs"),
        WordItem("malawi", "lake nation africa"),
        WordItem("malaysia", "split peninsula islands"),
        WordItem("maldives", "low coral atolls"),
        WordItem("mali", "sahel ancient empire"),
        WordItem("malta", "mediterranean fortress"),

        WordItem("marshall islands", "pacific scattered atolls"),
        WordItem("mauritania", "sahara ocean edge"),
        WordItem("mauritius", "volcanic island paradise"),

        WordItem("mexico", "sombrero culture land"),
        WordItem("micronesia", "tiny pacific states"),
        WordItem("moldova", "wine hill nation"),
        WordItem("monaco", "luxury microstate"),
        WordItem("mongolia", "steppe nomads"),
        WordItem("montenegro", "black mountain coast"),
        WordItem("morocco", "north africa gateway"),
        WordItem("mozambique", "indian ocean coast"),
        WordItem("myanmar", "golden pagoda land"),

        WordItem("namibia", "skeleton coast desert"),
        WordItem("nauru", "smallest island republic"),
        WordItem("nepal", "himalayan roof nation"),
        WordItem("netherlands", "below sea level"),
        WordItem("new zealand", "kiwi island nation"),
        WordItem("nicaragua", "central america lakes"),
        WordItem("niger", "sahara inland desert"),
        WordItem("nigeria", "africa population giant"),

        WordItem("north korea", "sealed regime state"),
        WordItem("north macedonia", "balkan inland nation"),
        WordItem("norway", "fjord coastal land"),

        WordItem("oman", "arabian peninsula coast"),
        WordItem("pakistan", "mountain river valley"),
        WordItem("palau", "micronesian reef nation"),
        WordItem("palestine", "historic contested land"),
        WordItem("panama", "canal connector nation"),

        WordItem("papua new guinea", "tribal rainforest islands"),
        WordItem("paraguay", "landlocked south america"),
        WordItem("peru", "inca mountain heritage"),
        WordItem("philippines", "7000 island nation"),
        WordItem("poland", "central europe plains"),
        WordItem("portugal", "iberian ocean edge"),

        WordItem("qatar", "rich desert peninsula"),
        WordItem("romania", "dracula carpathian land"),
        WordItem("russia", "largest spanning nation"),
        WordItem("rwanda", "thousand hills africa"),

        WordItem("saudi arabia", "oil desert kingdom"),
        WordItem("singapore", "modern city state"),
        WordItem("south africa", "rainbow nation"),
        WordItem("south korea", "tech pop culture hub"),
        WordItem("spain", "flamenco bull land"),
        WordItem("sri lanka", "teardrop island"),
        WordItem("sweden", "northern welfare land"),
        WordItem("switzerland", "neutral alpine banks"),
        WordItem("turkey", "bridge continent nation"),
        WordItem("ukraine", "grain breadbasket"),
        WordItem("united arab emirates", "skyline desert wealth"),
        WordItem("united kingdom", "island monarchy"),
        WordItem("united states", "global superpower"),
        WordItem("vietnam", "long coastal S shape"),
        WordItem("yemen", "arabian crisis land"),
        WordItem("zambia", "waterfall nation"),
        WordItem("zimbabwe", "ruins and rivers"),
      ],
    ),
    CategoryItem(
      title: "CITIES",
      image: "images/cities.png",
      words: [
        WordItem("delhi", "capital chaos"),
        WordItem("mumbai", "film finance hub"),
        WordItem("kolkata", "colonial intellect"),
        WordItem("chennai", "carnatic coast"),
        WordItem("bangalore", "silicon garden city"),
        WordItem("hyderabad", "biriyani tech mix"),
        WordItem("pune", "student cultural core"),
        WordItem("jaipur", "pink sandstone city"),
        WordItem("lucknow", "tehzeeb capital"),
        WordItem("chandigarh", "planned grid city"),
        WordItem("ahmedabad", "gandhi textile roots"),
        WordItem("surat", "diamond polishing hub"),
        WordItem("indore", "cleanest ranking city"),
        WordItem("bhopal", "lake tragedy memory"),
        WordItem("patna", "ancient river capital"),
        WordItem("kochi", "spice port history"),
        WordItem("goa", "beach party coast"),
        WordItem("varanasi", "oldest living city"),

        WordItem("new york", "skyscraper finance core"),
        WordItem("los angeles", "cinema dream land"),
        WordItem("london", "fog monarchy center"),
        WordItem("paris", "fashion river arc"),
        WordItem("berlin", "divided history capital"),
        WordItem("madrid", "royal football nation"),
        WordItem("rome", "ancient empire heart"),
        WordItem("barcelona", "gaudi architecture coast"),
        WordItem("amsterdam", "canal bike city"),
        WordItem("vienna", "classical music capital"),
        WordItem("prague", "fairy tale bridges"),
        WordItem("budapest", "danube twin city"),
        WordItem("warsaw", "rebuilt war capital"),

        WordItem("tokyo", "neon tech maze"),
        WordItem("osaka", "street food energy"),
        WordItem("seoul", "kpop tech culture"),
        WordItem("beijing", "forbidden capital"),
        WordItem("shanghai", "financial skyline giant"),
        WordItem("hong kong", "vertical trading hub"),

        WordItem("bangkok", "temple nightlife mix"),
        WordItem("singapore", "clean city state"),
        WordItem("dubai", "desert luxury towers"),
        WordItem("doha", "oil wealth skyline"),
        WordItem("kuala lumpur", "petronas twin towers"),
        WordItem("jakarta", "sinking mega capital"),

        WordItem("chicago", "windy jazz city"),
        WordItem("houston", "space mission base"),
        WordItem("miami", "latin beach nightlife"),
        WordItem("san francisco", "golden tech bridge"),
        WordItem("las vegas", "casino illusion land"),
        WordItem("boston", "harvard history hub"),
        WordItem("seattle", "rainy tech birthplace"),

        WordItem("toronto", "diverse skyline canada"),
        WordItem("vancouver", "mountain ocean mix"),

        WordItem("sydney", "opera harbour view"),
        WordItem("melbourne", "art coffee capital"),
        WordItem("auckland", "volcanic island city"),

        WordItem("cape town", "table mountain view"),
        WordItem("johannesburg", "gold mining heart"),

        WordItem("cairo", "pyramid nile edge"),
        WordItem("nairobi", "savannah capital"),

        WordItem("moscow", "red square frost"),
        WordItem("istanbul", "two continent bridge"),

        WordItem("athens", "ancient democracy origin"),
        WordItem("lisbon", "atlantic explorer port"),
        WordItem("dublin", "green literary city"),

        WordItem("zurich", "banking precision hub"),
        WordItem("geneva", "peace organization base"),
        WordItem("brussels", "eu headquarters center"),

        WordItem("reykjavik", "volcanic ice capital"),
        WordItem("helsinki", "design cold capital"),
        WordItem("oslo", "fjord government hub"),
        WordItem("stockholm", "island capital spread"),

        WordItem("venice", "floating canal maze"),
        WordItem("florence", "renaissance art heart"),
        WordItem("naples", "pizza origin coast"),

        WordItem("riyadh", "desert capital core"),
        WordItem("jeddah", "red sea gateway"),

        WordItem("tehran", "ancient modern blend"),
        WordItem("baghdad", "historical river city"),
      ],
    ),
    CategoryItem(
      title: "SPORTS",
      image: "images/sports.png",
      words: [
        WordItem("cricket", "bat and wicket duel"),
        WordItem("football", "goal net chase"),
        WordItem("basketball", "ring dunk game"),
        WordItem("baseball", "diamond run sport"),
        WordItem("tennis", "racket rally points"),
        WordItem("badminton", "fast shuttle exchange"),
        WordItem("hockey", "stick ice turf"),
        WordItem("volleyball", "net air spike"),
        WordItem("table tennis", "mini fast rally"),
        WordItem("golf", "hole precision swing"),

        WordItem("kabaddi", "hold breath tag"),
        WordItem("kho kho", "direction chase game"),
        WordItem("gilli danda", "stick flick hit"),

        WordItem("wrestling", "grip ground fight"),
        WordItem("boxing", "glove punch duel"),
        WordItem("mma", "mixed cage combat"),
        WordItem("karate", "strike discipline art"),
        WordItem("judo", "throw balance art"),
        WordItem("taekwondo", "kick speed art"),
        WordItem("sumo", "circle push force"),

        WordItem("formula 1", "fastest wheel machines"),
        WordItem("motogp", "two wheel speed"),
        WordItem("cycling", "pedal endurance race"),
        WordItem("horse racing", "saddle speed track"),
        WordItem("car racing", "engine track sprint"),

        WordItem("swimming", "water lane race"),
        WordItem("surfing", "wave balance ride"),
        WordItem("water polo", "pool ball combat"),
        WordItem("diving", "platform water entry"),

        WordItem("rowing", "synchronized oar pull"),
        WordItem("canoeing", "single boat paddle"),
        WordItem("kayaking", "narrow water glide"),

        WordItem("archery", "arrow precision aim"),
        WordItem("shooting", "target trigger sport"),
        WordItem("fencing", "blade touch duel"),

        WordItem("billiards", "cue ball pockets"),
        WordItem("snooker", "precision table shots"),
        WordItem("darts", "wall point throw"),

        WordItem("skiing", "snow slope glide"),
        WordItem("snowboarding", "board snow slide"),
        WordItem("ice skating", "blade ice glide"),
        WordItem("ice hockey", "puck frozen battle"),
        WordItem("bobsleigh", "ice tunnel speed"),

        WordItem("skateboarding", "wheel trick flips"),
        WordItem("rock climbing", "vertical grip climb"),
        WordItem("parkour", "urban obstacle flow"),

        WordItem("skydiving", "air free fall"),

        WordItem("chess", "king strategy board"),
        WordItem("ludo", "dice home race"),
        WordItem("carrom", "flick pocket board"),

        WordItem("esports", "digital arena battles"),
        WordItem("poker", "card bluff game"),

        WordItem("chessboxing", "mind punch combo"),
        WordItem("quidditch", "flying broom sport"),

        WordItem("ultimate frisbee", "flying disc pass"),
        WordItem("frisbee golf", "disc target holes"),
      ],
    ),
    CategoryItem(
      title: "GAMES",
      image: "images/games.png",
      words: [
        WordItem("pubg", "last circle survival"),
        WordItem("bgmi", "mobile battle royale"),
        WordItem("free fire", "quick survival match"),
        WordItem("clash of clans", "base raid strategy"),
        WordItem("clash royale", "card tower duel"),
        WordItem("subway surfers", "endless train run"),
        WordItem("temple run", "ancient escape chase"),
        WordItem("candy crush", "sweet match puzzle"),
        WordItem("ludo king", "dice home race"),
        WordItem("gta", "open world crime"),

        WordItem("minecraft", "block world build"),
        WordItem("fortnite", "building battle drop"),
        WordItem("call of duty", "military shooter core"),
        WordItem("fifa", "football simulation match"),
        WordItem("need for speed", "street racing chase"),

        WordItem("assassin's creed", "hidden blade history"),
        WordItem("far cry", "island chaos survival"),
        WordItem("red dead redemption", "wild west outlaw"),
        WordItem("cyberpunk", "neon future city"),

        WordItem("ludo", "dice board classic"),
        WordItem("chess", "king strategy war"),
        WordItem("carrom", "flick pocket board"),
        WordItem("snake and ladder", "luck climb fall"),
        WordItem("tic tac toe", "three line win"),

        WordItem("tekken", "fighting combo arena"),
        WordItem("mortal kombat", "fatality combat game"),
        WordItem("street fighter", "arcade punch duel"),

        WordItem("god of war", "spartan rage myth"),
        WordItem("among us", "imposter space vote"),
        WordItem("fall guys", "wacky obstacle race"),
        WordItem("angry birds", "slingshot structure crash"),
        WordItem("doodle jump", "endless platform climb"),
        WordItem("flappy bird", "tap pipe survival"),

        WordItem("asphalt", "arcade car racing"),
        WordItem("mario kart", "cartoon kart chaos"),
        WordItem("forza horizon", "realistic open racing"),
        WordItem("gran turismo", "driving simulation pro"),

        WordItem("pokemon", "monster capture journey"),
        WordItem("zelda", "hyrule hero quest"),
        WordItem("super mario", "pipe rescue world"),
        WordItem("roblox", "user made worlds"),

        WordItem("valorant", "agent tactical shooter"),
        WordItem("csgo", "bomb defuse classic"),
        WordItem("apex legends", "hero squad battle"),
        WordItem("overwatch", "hero shooter team"),
        WordItem("rainbow six siege", "breach tactical ops"),

        WordItem("dota 2", "ancient defense war"),
        WordItem("league of legends", "champion lane battle"),
        WordItem("counter strike", "terrorist vs counter"),

        WordItem("world of warcraft", "fantasy MMO realm"),
        WordItem("diablo", "hell dungeon loot"),
        WordItem("starcraft", "space faction war"),
        WordItem("hearthstone", "card battle spells"),

        WordItem("overcooked", "chaotic kitchen teamwork"),
        WordItem("left 4 dead", "zombie squad survival"),
        WordItem("half life", "alien science chaos"),
        WordItem("portal", "physics puzzle gates"),

        WordItem("bioshock", "underwater dystopia"),
        WordItem("dark souls", "punishing boss fights"),
        WordItem("witcher", "monster hunter saga"),
        WordItem("skyrim", "dragon open world"),
        WordItem("fallout", "post nuclear wasteland"),

        WordItem("mass effect", "space dialogue choices"),
        WordItem("dragon age", "fantasy party RPG"),
        WordItem("the last of us", "infected emotional survival"),
        WordItem("horizon zero dawn", "robot beast hunt"),
        WordItem("ghost of tsushima", "samurai honor war"),
      ],
    ),
    CategoryItem(
      title: "BODY&HEALTH",
      image: "images/fitness.png",
      words: [
        WordItem("head", "thinking control center"),
        WordItem("eye", "vision sensor"),
        WordItem("ear", "sound receiver"),
        WordItem("nose", "air filter"),
        WordItem("mouth", "food entry point"),
        WordItem("teeth", "food grinders"),
        WordItem("tongue", "taste muscle"),
        WordItem("neck", "head connector"),

        WordItem("shoulder", "arm support joint"),
        WordItem("arm", "lifting limb"),
        WordItem("elbow", "bend hinge"),
        WordItem("hand", "grasp tool"),
        WordItem("finger", "fine control digit"),

        WordItem("chest", "breathing shield"),
        WordItem("stomach", "food digestion zone"),
        WordItem("back", "body support frame"),
        WordItem("waist", "body middle band"),

        WordItem("leg", "movement pillar"),
        WordItem("knee", "leg joint bend"),
        WordItem("foot", "ground contact base"),

        WordItem("heart", "blood pump engine"),
        WordItem("brain", "command processor"),
        WordItem("lungs", "oxygen exchange unit"),
        WordItem("liver", "detox factory"),
        WordItem("kidney", "filter system"),
        WordItem("intestine", "nutrient absorber"),
        WordItem("bones", "body framework"),
        WordItem("muscles", "movement power"),
        WordItem("blood", "transport fluid"),
        WordItem("skin", "outer protection layer"),

        WordItem("exercise", "body activity"),
        WordItem("running", "fast foot motion"),
        WordItem("jogging", "slow run rhythm"),
        WordItem("walking", "basic movement pace"),
        WordItem("stretching", "flex flexibility"),
        WordItem("yoga", "body balance pose"),
        WordItem("meditation", "mind stillness"),
        WordItem("workout", "fitness routine"),
        WordItem("gym", "strength training space"),
        WordItem("cardio", "heart endurance work"),
        WordItem("strength", "force building"),

        WordItem("doctor", "health fixer"),
        WordItem("nurse", "care assistant"),
        WordItem("hospital", "treatment center"),
        WordItem("medicine", "healing substance"),
        WordItem("tablet", "swallow dose"),
        WordItem("injection", "direct entry shot"),
        WordItem("checkup", "health inspection"),
        WordItem("diagnosis", "problem finding"),
        WordItem("treatment", "recovery process"),
        WordItem("surgery", "internal repair"),

        WordItem("fever", "temperature rise"),
        WordItem("cold", "viral chill"),
        WordItem("cough", "airway reflex"),
        WordItem("pain", "body warning signal"),
        WordItem("headache", "brain pressure feel"),
        WordItem("injury", "body damage"),
        WordItem("infection", "microbe attack"),
        WordItem("allergy", "immune overreaction"),
        WordItem("fatigue", "energy drop"),
        WordItem("weakness", "low strength state"),

        WordItem("diet", "food control plan"),
        WordItem("nutrition", "body fuel system"),
        WordItem("protein", "muscle builder"),
        WordItem("vitamins", "body boosters"),
        WordItem("hydration", "water balance"),

        WordItem("sleep", "recovery mode"),
        WordItem("rest", "energy pause"),
        WordItem("hygiene", "clean habit system"),

        WordItem("mental health", "mind balance state"),
        WordItem("stress", "pressure overload"),
        WordItem("anxiety", "future worry loop"),
        WordItem("depression", "low mood state"),
      ],
    ),
    CategoryItem(
      title: "BRANDS",
      image: "images/brands.png",
      words: [
        WordItem("apple", "fruit logo tech"),
        WordItem("samsung", "korean tech giant"),
        WordItem("sony", "playstation creator"),
        WordItem("lg", "life’s good tag"),
        WordItem("hp", "printer laptop maker"),
        WordItem("dell", "business pc focus"),
        WordItem("lenovo", "thinkpad owner"),
        WordItem("asus", "rog gaming brand"),
        WordItem("acer", "budget laptop maker"),
        WordItem("microsoft", "windows system creator"),
        WordItem("intel", "processor chip core"),
        WordItem("nvidia", "gpu ai power"),

        WordItem("oneplus", "flagship killer phones"),
        WordItem("xiaomi", "budget tech ecosystem"),
        WordItem("oppo", "camera selfie focus"),
        WordItem("vivo", "portrait phone brand"),
        WordItem("realme", "young budget phones"),

        WordItem("bmw", "driving machine slogan"),
        WordItem("audi", "four ring luxury"),
        WordItem("mercedes", "three star luxury"),
        WordItem("tesla", "electric car revolution"),
        WordItem("toyota", "reliability car giant"),
        WordItem("honda", "engine efficiency leader"),
        WordItem("hyundai", "korean auto export"),
        WordItem("kia", "modern design cars"),
        WordItem("ford", "american muscle origin"),
        WordItem("chevrolet", "bowtie car brand"),
        WordItem("volkswagen", "people’s car origin"),
        WordItem("skoda", "european budget cars"),
        WordItem("tata", "indian industrial giant"),
        WordItem("mahindra", "rugged suv maker"),
        WordItem("suzuki", "compact city cars"),

        WordItem("nike", "just do it"),
        WordItem("adidas", "three stripe brand"),
        WordItem("puma", "leaping cat logo"),
        WordItem("zara", "fast fashion trend"),
        WordItem("h&m", "affordable fashion chain"),
        WordItem("gucci", "luxury fashion icon"),
        WordItem("prada", "italian luxury house"),
        WordItem("louis vuitton", "lv monogram bags"),
        WordItem("versace", "medusa luxury style"),
        WordItem("levis", "denim jeans origin"),

        WordItem("mcdonalds", "golden arches fastfood"),
        WordItem("kfc", "colonel fried chicken"),
        WordItem("burger king", "flame grill burgers"),
        WordItem("dominos", "pizza delivery speed"),
        WordItem("pizza hut", "pan pizza chain"),
        WordItem("starbucks", "coffee green siren"),

        WordItem("coca cola", "red fizzy drink"),
        WordItem("pepsi", "blue cola rival"),
        WordItem("nestle", "food giant brand"),
        WordItem("cadbury", "chocolate purple wrap"),
        WordItem("amul", "milk cooperative brand"),
        WordItem("patanjali", "ayurvedic product chain"),

        WordItem("reliance", "business empire india"),
        WordItem("flipkart", "online shopping pioneer"),
        WordItem("paytm", "digital wallet system"),
        WordItem("big bazaar", "retail hypermarket chain"),

        WordItem("jio", "cheap data revolution"),
        WordItem("airtel", "telecom network leader"),
        WordItem("vodafone", "red network brand"),
        WordItem("bsnl", "government telecom service"),
        WordItem("idea", "network merged brand"),

        WordItem("tata sky", "satellite tv service"),
      ],
    ),
  ];
}
